### ISSUE TITLE
Analytics Silent E

### ISSUE THREAD

**Issue by chrismkim** [erinmgriffith/Active-projects#106]
I would like to use my analytics account to track our site. Here is the tracking code

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-110400674-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-110400674-1');
</script>

**Comment by erinmgriffith** [comment]
Done and updated
