### ISSUE TITLE
Browser Testing

### ISSUE THREAD

**Issue by erinmgriffith** [erinmgriffith/Active-projects#53]
Test site performance in the following browsers for each state and device record notes and pics with issues
 - [ ] Opera
       - [ ] Desktop
       - [ ] Mobile
       - [ ] IPad             
 - [x] Safari
      - [x] Desktop
       - [x] Mobile
       - [x] IPad
 - [x] Chrome
      - [x] Desktop
       - [x] Mobile
       - [x] IPad
 - [ ] IE
      - [ ] Desktop
       - [ ] Mobile
       - [ ] IPad
 - [ ] Firefox
      - [x] Desktop
       - [ ] Mobile
       - [ ] IPad
 - [ ] Mozilla
      - [ ] Desktop
       - [ ] Mobile
       - [ ] IPad
 - [ ] Netscape
      - [ ] Desktop
       - [ ] Mobile
       - [ ] IPad

**Comment by chrismkim** [comment]
- [ ] On mobile, the text is weird next to the pictures on the "about us" section
- [ ] On smaller desktop and bigger notebook, the services tab gets cut off at the top
