### ISSUE TITLE
Prepare for meeting with Jenny

### ISSUE THREAD

**Issue by erinmgriffith** [erinmgriffith/Active-projects#60]
- [x] Create list of topics to address during initial meeting

- [x] Create list of elements present on current site and potential elements that they might be interested in.

**Comment by erinmgriffith** [comment]
To discuss-
   - [ ] identify target audience and target audience needs
   - [ ] identify business needs
   - [ ] purpose of site- what it will be primarily designed to do
   - [ ] specific design requirements
   - [ ] specific functional requirements 
   - [ ] specific technical requirements

**Comment by erinmgriffith** [comment]
**target audience-** 
     potential buyers: older, high income, want rural lifestyle, quiet, full-time or vacation homes. Out of town or even nation, wanting to relocate, willing to travel to view homes. Homesteading, simplicity, natur
     potential sellers: middle age or retirees who no longer want to or are able to live in remote location, locals, often lower income. Land

**business needs**
- stay in contact with potential customers
- attract both potential buyers and sellers
- target specifically serious buyers 

**purpose**
- bring in potential buyers
- appeal primarily to serious buyers 
- educate potential buyers on area and lifestyle 
- provide detailed information on featured properties

**design preferences**
- mimbreno-derived art and pics
- clean and easily navigable
- original and rememberable
- dove

required/desired elements
- broker info
- featured listings
- general land listings (styled)
- general residential listings (styled)
- newsletter signup
- area info
- links to more area and community info
- contact info
- directions to office
- RPH (maybe, in back)
- buyers section
- sellers section

**functional requirements**
- form function and validation for requesting and keeping email addresses
- file read info from mls listing
- links to realtor.com and  various real estate articles
- allow users to find info on area and lifestyle
- must be extensible to allow space for additional features to featured listings



technical requirements: none

**Comment by chrismkim** [comment]
Really great summation.
