### ISSUE TITLE
GoDaddy SEO

### ISSUE THREAD

**Issue by erinmgriffith** [erinmgriffith/Active-projects#66]
We are signed up for the GoDaddy SEO service for Javalina. The dashboard however shows that we are tracking 11 keywords, but that there is no change or visibility in any of them and visibility is 0.Research how Go Daddy  SEO service works.

**Comment by chrismkim** [comment]
Godaddy bought ManageWP and that site monitoring link is directly from that. Some functionalty exists but its meant for only Wordpress sites. 

Therefore we need to track our SEO with analytics account external to godaddy. I have started this process in a new issue. Also we need to now use something else or omit the seo page from our client monthly reports. I think probably ill just make a page that looks similar and populate it with our analytics results.
