### ISSUE TITLE
Get Pics

### ISSUE THREAD

**Issue by erinmgriffith** [erinmgriffith/Active-projects#83]
Need the following pics/screenshots
- [x] pics of Bella
- [x] Barkus
- [x] Kitty
- [x] Erin
- [x] Chris
- [ ] the house
- [x] javalina
- [x]  polished plum
- [x] CN
- [ ] marketing- google analytics?
- [ ] stock-type pics

**Comment by chrismkim** [comment]
sent some bark and bella to phone
and here is mine
![chris](https://user-images.githubusercontent.com/8686795/29543033-910d9106-869b-11e7-9243-1f77f9638e7b.png)

**Comment by chrismkim** [comment]
Lets meet about the pics when you have time. can go over each page and plan.
