### ISSUE TITLE
On page SEO

### ISSUE THREAD

**Issue by erinmgriffith** [erinmgriffith/Active-projects#88]
- [x] correct page titles
- [x] meta tags
- [x] other as needed

**Comment by chrismkim** [comment]
title tag should be "Web Design, Development, and Marketing - Silent E Studio

**Comment by chrismkim** [comment]
needs a Rel="canonical"

**Comment by chrismkim** [comment]
meta for page

Web Design, Development, and Marketing. Bring your local business to the wider world. Proudly serving the Silver City NM business community and desert southwest.
